"""主程序入口"""
from datetime import datetime
from .config import Config
from .paper_fetcher import get_papers
from .llm_analyzer import LLMAnalyzer
from .notifier import Notifier


def main() -> None:
    """主函数"""
    try:
        # 验证配置
        print("🔍 正在验证配置...")
        Config.validate()
        print("✅ 配置验证通过")
    except Exception as e:
        print(f"❌ 配置验证失败: {type(e).__name__}: {e}")
        import traceback
        traceback.print_exc()
        raise

    print(f"🚀 开始任务，使用模型: {Config.MODEL_NAME}")

    # 初始化客户端和分析器
    analyzer = LLMAnalyzer()
    notifier = Notifier()

    # 获取论文（默认获取昨天的论文）
    print("\n📰 开始获取 HuggingFace Daily Papers...")
    print(f"📊 配置: MAX_PAPERS={Config.MAX_PAPERS}")
    papers = get_papers()
    print(f"✅ 获取到 {len(papers)} 篇论文（配置限制: {Config.MAX_PAPERS}）")

    if not papers:
        print("❌ 没有获取到论文，可能是该日期没有论文或 API 访问失败")
        return

    # 打印论文列表
    print("\n论文列表:")
    for i, paper in enumerate(papers, 1):
        print(f"  {i}. {paper.title}")
        print(f"     链接: {paper.link}")
        print(f"     摘要长度: {len(paper.summary)} 字符")

    # 生成 HTML 报告
    print("\n🤖 开始分析论文...")
    report_html = ""

    for i, paper in enumerate(papers, 1):
        print(f"\n[{i}/{len(papers)}] 正在分析: {paper.title}...")
        print(f"    开始时间: {datetime.now().strftime('%H:%M:%S')}")
        try:
            summary = analyzer.summarize(paper)
            print(f"    结束时间: {datetime.now().strftime('%H:%M:%S')}")
            print(f"  ✅ 分析完成，返回内容长度: {len(summary) if summary else 0} 字符")
            if summary:
                print(f"  内容预览: {summary[:100]}...")
                report_html += summary + "\n"
            else:
                print(f"  ⚠️ 返回内容为空")
        except Exception as e:
            print(f"    结束时间: {datetime.now().strftime('%H:%M:%S')}")
            print(f"  ❌ 分析出错: {type(e).__name__}: {e}")
            import traceback
            traceback.print_exc()
            # 继续处理下一篇论文，不中断整个流程
            continue

    print(f"\n📊 报告统计:")
    print(f"  总论文数: {len(papers)}")
    print(f"  报告内容长度: {len(report_html)} 字符")

    # 发送邮件
    if report_html.strip():
        print("\n📧 开始发送邮件...")
        try:
            notifier.send_email(report_html)
            print("✅ 报告已发送！")
        except Exception as e:
            print(f"\n⚠️ 邮件发送失败，但报告内容已生成")
            # 保存报告到文件作为备份
            from datetime import datetime
            backup_file = f"daily_paper_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
            try:
                with open(backup_file, 'w', encoding='utf-8') as f:
                    f.write(f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Daily Paper Report - {datetime.now().strftime('%Y-%m-%d')}</title>
    <style>
        body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 1200px; margin: 0 auto; padding: 20px; }}
        h2 {{ color: #2c3e50; }}
        h3 {{ color: #34495e; margin-top: 20px; }}
        a {{ color: #3498db; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        hr {{ border: none; border-top: 1px solid #eee; margin: 20px 0; }}
        .footer {{ font-size: small; color: gray; margin-top: 30px; }}
    </style>
</head>
<body>
    <h2>今日热门论文速递</h2>
    <p>关注领域: {Config.KEYWORDS}</p>
    <p>生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    <hr>
    {report_html}
    <div class="footer">
        <p>Generated by {Config.MODEL_NAME}</p>
    </div>
</body>
</html>
""")
                print(f"💾 报告已保存到文件: {backup_file}")
                print(f"   你可以在浏览器中打开此文件查看报告")
            except Exception as save_error:
                print(f"⚠️ 保存报告文件也失败: {save_error}")
            print(f"\n💡 建议检查邮件配置或网络连接后重试")
    else:
        print("\n⚠️ 没有生成报告内容")
        print("可能的原因:")
        print("  1. LLM API 调用失败")
        print("  2. LLM 返回空内容")
        print("  3. 论文数据获取失败")


if __name__ == "__main__":
    main()
