"""通知推送模块"""
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from .config import Config


class Notifier:
    """邮件通知推送器"""

    @staticmethod
    def send_email(html_content: str) -> None:
        """
        发送 HTML 格式的邮件

        Args:
            html_content: HTML 格式的邮件内容
        """
        msg = MIMEMultipart()
        msg['From'] = Config.EMAIL_SENDER
        msg['To'] = Config.EMAIL_RECEIVER
        msg['Subject'] = f"🚀 HuggingFace Daily ({datetime.now().strftime('%Y-%m-%d')})"

        body = f"""
        <html>
          <head>
            <style>
              body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
              h2 {{ color: #2c3e50; }}
              h3 {{ color: #34495e; margin-top: 20px; }}
              a {{ color: #3498db; text-decoration: none; }}
              a:hover {{ text-decoration: underline; }}
              hr {{ border: none; border-top: 1px solid #eee; margin: 20px 0; }}
              .footer {{ font-size: small; color: gray; margin-top: 30px; }}
            </style>
          </head>
          <body>
            <h2>今日热门论文速递</h2>
            <p>关注领域: {Config.KEYWORDS}</p>
            <hr>
            {html_content}
            <div class="footer">
              <p>Generated by {Config.MODEL_NAME} via GitHub Actions</p>
            </div>
          </body>
        </html>
        """
        msg.attach(MIMEText(body, 'html'))

        try:
            server = smtplib.SMTP(Config.SMTP_SERVER, Config.SMTP_PORT)
            server.starttls()
            server.login(Config.EMAIL_SENDER, Config.EMAIL_PASSWORD)
            server.sendmail(Config.EMAIL_SENDER, Config.EMAIL_RECEIVER, msg.as_string())
            server.quit()
            print("✅ 邮件发送成功！")
        except Exception as e:
            print(f"❌ 邮件发送失败: {e}")
            raise
